# ~/.config/alacritty/alacritty.toml
[window]
opacity = 0.8
padding = { x = 10, y = 10 }
decorations = "none"

[font]
normal = { family = "Meslo LGM Nerd Font", style = "Regular" }
size = 16.0

[colors.primary]
background = "#141415"
foreground = "#c7c6c6"

[colors.normal]
black   = "#1c1e22"
red     = "#be8c8c"
green   = "#9da380"
yellow  = "#c2ac7b"
blue    = "#8cadc6"
magenta = "#b9a3ba"
cyan    = "#a3b8b6"
white   = "#c7c6c6"

[colors.bright]
black   = "#51575d"
red     = "#d99c9a"
green   = "#b6c8b9"
yellow  = "#d9c88a"
blue    = "#a5bfe0"
magenta = "#cfc2d4"
cyan    = "#c4d2d0"
white   = "#e0e0e0"

[env]
TERM = "xterm-256color"

[terminal]

