#List of plugins
set -g @plugin 'tmux-plugins/tpm'
set-option -g prefix C-s
set-option -g  mouse on
set -g base-index 1
set -g renumber-windows on   
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=white bg=#444444"
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""


set -a terminal-features "tmux-256color:RGB"

unbind -n WheelUpPane
unbind -n WheelDownPane

bind -n WheelUpPane if-shell -F '#{mouse_any_flag}' 'send-keys -M' 'copy-mode -e'
bind -n WheelDownPane if-shell -F '#{mouse_any_flag}' 'send-keys -M' 'send-keys -M'
run '~/.tmux/plugins/tpm/tpm'
