#! /bin/sh
~/.config/bspwm/autostart.sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Syntax: bspc rule -a <class_name> desktop='^<workspace_number>'
bspc rule -a Brave-browser desktop='^1'   # Firefox opens on workspace 1
bspc rule -a org.wezfurlong.wezterm desktop='^2' # Terminal on workspace 2
bspc rule -a Nemo desktop='^3'    # File manager on workspace 3
bspc rule -a vlc desktop='^1'    # File manager on workspace 3
bspc rule -a qBittorrent desktop='^10'   # Discord on workspace 4

bspc config border_width         0
bspc config window_gap          0
bspc config top_padding 45

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
