// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.uia.enable", 2);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "df8f18b4-a688-4c87-b003-0191a4664fee");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1761587287);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1761587317);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "c081d75c-7561-470c-9a9f-80e9e1cab2c4");
user_pref("browser.contextual-services.contextId.rotation-in-days", 7);
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1761587285);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1761587285);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 160);
user_pref("browser.ml.chat.nimbus", "ai-chatbot-page-summarization-mvp-treatment-a-callout-badge-rollout-v2:treatment-a-callout-badge");
user_pref("browser.newtabpage.activity-stream.impressionId", "{7c70a6b7-6c86-445d-97c7-cb36a8d2c462}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.trainhopAddon.version", "145.1.20251009.134757");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1761587286);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1761587287912");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1761608887912");
user_pref("browser.search.region", "BD");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20251013184459");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1761587317");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20251013184459");
user_pref("browser.startup.homepage_override.mstone", "144.0");
user_pref("browser.startup.lastColdStartupCheck", 1761587317);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.toolbarbuttons.introduced.sidebar-button", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1761587318);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"sidebar-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 3);
user_pref("captchadetection.lastSubmission", 1761587);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "af5c397b-d46c-4eb5-aef3-55406b772769");
user_pref("datareporting.dau.cachedUsageProfileID", "0e30c848-c866-4d75-9cbd-00dbbf563bce");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1761587286095");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "144.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "BD");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "b96ee2d285934535b1d8f08dc517770b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20251013184459");
user_pref("extensions.lastAppVersion", "144.0");
user_pref("extensions.lastPlatformVersion", "144.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"7b39f3fa-ab8d-41ac-afea-7560548d35bd\",\"formautofill@mozilla.org\":\"fa51b0f9-c50c-40b0-ad16-6c12485aed5d\",\"ipp-activator@mozilla.com\":\"f8482aed-bb22-4d15-9fd3-60a0c59d3f28\",\"pictureinpicture@mozilla.org\":\"77f13700-83d5-48c1-be7a-270c26844b2d\",\"addons-search-detection@mozilla.com\":\"517cd465-267b-49a2-8357-7defdb76c351\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"2e3075ec-818c-44ae-af0a-ecf841b733cc\",\"default-theme@mozilla.org\":\"ba269b7e-27f5-43e0-8031-8d85c41f9f8d\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 2);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "a3906a17-795d-4db3-bc78-f3aef3fd5e33");
user_pref("nimbus.profilesdatastoreservice.read.enabled", true);
user_pref("nimbus.profilesdatastoreservice.sync.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherWidth\":0,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.main.tools", "aichat,syncedtabs,history,bookmarks");
user_pref("sidebar.nimbus", "upgraded-sidebar-138-broad-rollout:rollout-treatment");
user_pref("sidebar.notification.badge.aichat", true);
user_pref("sidebar.revamp", true);
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("signon.firefoxRelay.showToAllBrowsers", true);
user_pref("toolkit.profiles.storeID", "8ea87038");
user_pref("toolkit.startup.last_success", 1761587316);
user_pref("toolkit.telemetry.cachedClientID", "98401404-4839-4e16-a887-71b40a349fbd");
user_pref("toolkit.telemetry.cachedProfileGroupID", "360925db-7695-460f-b3db-2e9dd9d8a60f");
user_pref("toolkit.telemetry.previousBuildID", "20251013184459");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
